language: node_js
node_js:
  - "8"
  - "7"
  - "6"
  - "5"
  - "4.6"
  - "10"

sudo: false

script:
  - "npm run test-coverage"

after_script:
  - "npm install coveralls@2 && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
